<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita247e4585e48b7e7804cbe4b64719efd
{
    public static $prefixLengthsPsr4 = array (
        'c' => 
        array (
            'chillerlan\\Settings\\' => 20,
            'chillerlan\\QRCode\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'chillerlan\\Settings\\' => 
        array (
            0 => __DIR__ . '/..' . '/chillerlan/php-settings-container/src',
        ),
        'chillerlan\\QRCode\\' => 
        array (
            0 => __DIR__ . '/..' . '/chillerlan/php-qrcode/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita247e4585e48b7e7804cbe4b64719efd::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita247e4585e48b7e7804cbe4b64719efd::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInita247e4585e48b7e7804cbe4b64719efd::$classMap;

        }, null, ClassLoader::class);
    }
}
